repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0
    hooks:
      - id: terraform_fmt
        args:
          - --args=--check
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
      - id: terraform_tflint
      - id: terraform_tfsec
      - id: terraform_checkov
        verbose: true
        args:
          - --args=--quiet
          - --args=--skip-check CKV_DOCKER_4
          - --args=--skip-check CKV_DOCKER_2
          - --args=--skip-check CKV_DOCKER_3
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
